// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import RamenReviews__FormController from "./ramen_reviews/form_controller"
application.register("ramen-reviews--form", RamenReviews__FormController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
